### ISSUE TITLE
Coquille Partie "calcul des Matrices élémentaires" - Matrice de Masse élémentaire 

### ISSUE THREAD

**Issue by FatineBts** [Bertbk/course_fem#12]
Bonsoir,

je crois qu'il y a une coquille : phi i et phi j sont inversés 

![capture d ecran 2019-01-16 a 18 44 23](https://user-images.githubusercontent.com/23095219/51267767-c7ea1c00-19be-11e9-8bcc-834dacbe3788.png)

**Comment by FatineBts** [comment]
J'ai pas réussi à modifier directement (erreur GitHub ?) mais il me semble que dans la partie Neumann non homogène à la fin de la démonstration on a L2(partial omega) et pas L2(omega) ;)

\int\_{\partial\Omega} \abs{g - \dn u}^2\diff s = 0 = \norm{g-\dn u}\_{L^2(\partial\Omega)},

**Comment by Bertbk** [comment]
Merci beaucoup, c'est corrigé !

Vous ne pouvez pas modifier directement dans Github, vous devez lancer un Pull Request.
Deux solutions pour cela :
1. La classique : 
    - "Forker" le dépôt dans votre compte
    - Récupérer le code sur votre ordi (ou modifier dans github)
    - Créer une branche dédié
    ```
    git branch correction
    git checkout correction
    ```
    - Effectuer les modifications sur votre dépôt et les versionner
    ```
    git commit -m "blabla" -a
    git push
    ```
    - Après, si vous venez dans mon dépôt, on vous propose de faire un Pull Request
    - De mon côté, je valide (ou pas ;))

- Plus rapide : utilisez Prose.io. Un lien est fourni dans chaque page du cours sur la droite "Edit This Page". 
En réalité, Prose.io effectue, pour vous, toutes les étapes précédentes :)

Plus d'info dans [la doc de Github](https://help.github.com/articles/about-pull-requests/).

**Comment by FatineBts** [comment]
Je vous en prie ! 
La seconde solution est celle que j'ai essayé d'accomplir mais ça ne marchait pas. :) 
Bonne journée

**Comment by Bertbk** [comment]
Étrange... Merci encore pour les corrections !
