### ISSUE TITLE
Elements P2

### ISSUE THREAD

**Issue by FatineBts** [Bertbk/course_fem#14]
Bonjour, 

je crois qu'il y a une coquille partie Elements P2 :  \dsp    \phih\_{2} &=& 2 \varphih\_{2}\left(\varphih\_{2} - \frac{1}{2}\right)\\\\\\

Je n'ai pas réussi à modifier le code directement (la preuve en image ;)). 

![capture d ecran 2019-01-17 a 12 03 04](https://user-images.githubusercontent.com/23095219/51314490-15fb3000-1a50-11e9-99af-c2e3b7648d38.png)

Bonne journée

**Comment by Bertbk** [comment]
Merci c'est corrigé !

Etrange votre erreur, chez moi ça fonctionne...
