### ISSUE TITLE
Coquille formule intégration par parties 

### ISSUE THREAD

**Issue by FatineBts** [Bertbk/course_fem#4]
Il y a une coquille dans la formule d'intégration par parties (https://ljll.math.upmc.fr/bthierry/course/fem/fv_formules_integration/)

**Comment by Bertbk** [comment]
Je pense que vous parlez du "v" au lieu du "u" ? Si oui, merci c'est corrigé ! :-)
La prochaine fois, si vous le voulez, vous pouvez utiliser le lien vers "proser.io" pour faire un Pull Request très rapide :-)

**Comment by FatineBts** [comment]
Oui c'est ça. Très bien j'en prends note :).
